# Generated by Django 6.0.4 on 2026-06-20 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('club', models.CharField(max_length=200)),
                ('league', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('teaser', models.TextField(blank=True, help_text='Short preview shown when locked')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packs/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_premium', models.BooleanField(default=True)),
                ('stadium_name', models.CharField(blank=True, max_length=200)),
                ('stadium_capacity', models.CharField(blank=True, max_length=50)),
                ('stadium_location', models.CharField(blank=True, max_length=200)),
                ('stadium_atmosphere', models.CharField(blank=True, max_length=200)),
                ('stadium_description', models.TextField(blank=True)),
                ('city_best_areas', models.CharField(blank=True, max_length=300)),
                ('city_food', models.CharField(blank=True, max_length=300)),
                ('city_nightlife', models.CharField(blank=True, max_length=300)),
                ('city_tips', models.TextField(blank=True)),
                ('hotel_recommendation', models.CharField(blank=True, max_length=300)),
                ('hotel_area', models.CharField(blank=True, max_length=300)),
                ('hotel_area_reason', models.CharField(blank=True, max_length=500)),
                ('hotel_notes', models.TextField(blank=True)),
                ('transport_airport', models.CharField(blank=True, max_length=500)),
                ('transport_city', models.CharField(blank=True, max_length=500)),
                ('transport_stadium', models.CharField(blank=True, max_length=500)),
                ('transport_notes', models.TextField(blank=True)),
                ('food_local', models.CharField(blank=True, max_length=300)),
                ('food_restaurants', models.CharField(blank=True, max_length=500)),
                ('food_bars', models.CharField(blank=True, max_length=500)),
                ('food_notes', models.TextField(blank=True)),
                ('safety_general', models.CharField(blank=True, max_length=500)),
                ('safety_matchday', models.CharField(blank=True, max_length=500)),
                ('safety_areas', models.CharField(blank=True, max_length=500)),
                ('safety_notes', models.TextField(blank=True)),
                ('experiences_attractions', models.CharField(blank=True, max_length=500)),
                ('experiences_football', models.CharField(blank=True, max_length=500)),
                ('experiences_nightlife', models.CharField(blank=True, max_length=500)),
                ('experiences_notes', models.TextField(blank=True)),
                ('budget_flights', models.CharField(blank=True, max_length=200)),
                ('budget_hotel', models.CharField(blank=True, max_length=200)),
                ('budget_tickets', models.CharField(blank=True, max_length=200)),
                ('budget_food', models.CharField(blank=True, max_length=200)),
                ('budget_transport', models.CharField(blank=True, max_length=200)),
                ('budget_notes', models.TextField(blank=True)),
                ('map_stadium', models.CharField(blank=True, max_length=300)),
                ('map_transport', models.CharField(blank=True, max_length=300)),
                ('map_pub', models.CharField(blank=True, max_length=300)),
                ('map_hotel_area', models.CharField(blank=True, max_length=300)),
                ('map_notes', models.TextField(blank=True)),
                ('contact_emergency', models.CharField(blank=True, max_length=100)),
                ('contact_police', models.CharField(blank=True, max_length=200)),
                ('contact_taxi', models.CharField(blank=True, max_length=200)),
                ('contact_stadium', models.CharField(blank=True, max_length=200)),
                ('contact_notes', models.TextField(blank=True)),
                ('flight_link', models.URLField(blank=True)),
                ('hotel_link', models.URLField(blank=True)),
                ('ticket_link', models.URLField(blank=True)),
                ('tour_link', models.URLField(blank=True)),
                ('itinerary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='packs.pack')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='packs.pack')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UnlockedPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packs.pack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pack')},
            },
        ),
    ]
