# Generated by Django 6.0.4 on 2026-06-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='image',
        ),
        migrations.AddField(
            model_name='pack',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
