# Generated by Django 6.0.4 on 2026-04-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('club', models.CharField(max_length=200)),
                ('league', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('itinerary', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, upload_to='packs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
