# Generated by Django 6.0.4 on 2026-05-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='flight_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='hotel_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='ticket_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='tour_link',
            field=models.URLField(blank=True),
        ),
    ]
