# Generated by Django 6.0.4 on 2026-05-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pack_flight_link_pack_hotel_link_pack_ticket_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='teaser',
            field=models.TextField(blank=True),
        ),
    ]
