# Generated by Django 6.0.4 on 2026-05-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pack_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='is_premium',
            field=models.BooleanField(default=True),
        ),
    ]
