# Generated by Django 6.0.4 on 2026-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pack_price_alter_pack_teaser_unlockedpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='stadium_atmosphere',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pack',
            name='stadium_capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pack',
            name='stadium_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='stadium_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pack',
            name='stadium_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
