# Generated by Django 6.0.4 on 2026-05-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pack_stadium_atmosphere_pack_stadium_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='city_best_areas',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pack',
            name='city_food',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pack',
            name='city_nightlife',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pack',
            name='city_tips',
            field=models.TextField(blank=True),
        ),
    ]
