# Generated by Django 6.0.4 on 2026-05-25 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pack_city_best_areas_pack_city_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='core.pack')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
