# Generated by Django 6.0.4 on 2026-05-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_timelineentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='hotel_area',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pack',
            name='hotel_area_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pack',
            name='hotel_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='hotel_recommendation',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
