# Generated by Django 6.0.4 on 2026-05-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pack_hotel_area_pack_hotel_area_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='transport_airport',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pack',
            name='transport_city',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pack',
            name='transport_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='transport_stadium',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
