# Generated by Django 6.0.4 on 2026-05-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pack_transport_airport_pack_transport_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='food_bars',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pack',
            name='food_local',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pack',
            name='food_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='food_restaurants',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
