# Generated by Django 6.0.4 on 2026-05-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pack_food_bars_pack_food_local_pack_food_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='safety_areas',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pack',
            name='safety_general',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pack',
            name='safety_matchday',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pack',
            name='safety_notes',
            field=models.TextField(blank=True),
        ),
    ]
