# Generated by Django 6.0.4 on 2026-05-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pack_safety_areas_pack_safety_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='experiences_attractions',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pack',
            name='experiences_football',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pack',
            name='experiences_nightlife',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pack',
            name='experiences_notes',
            field=models.TextField(blank=True),
        ),
    ]
