# Generated by Django 6.0.4 on 2026-05-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pack_experiences_attractions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='budget_flights',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pack',
            name='budget_food',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pack',
            name='budget_hotel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pack',
            name='budget_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='budget_tickets',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pack',
            name='budget_transport',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
