# Generated by Django 6.0.4 on 2026-05-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pack_budget_flights_pack_budget_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='map_hotel_area',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pack',
            name='map_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='map_pub',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pack',
            name='map_stadium',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pack',
            name='map_transport',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
