# Generated by Django 6.0.4 on 2026-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pack_map_hotel_area_pack_map_notes_pack_map_pub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='contact_emergency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pack',
            name='contact_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='contact_police',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pack',
            name='contact_stadium',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pack',
            name='contact_taxi',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
